version: '3'

services:

  postgres:
    extends:
      file: docker-compose-db.yml
      service: postgres

  service-product:
    container_name: vs-academy-service-product
    image: service-product
    environment:
      DATABASE_URL: "postgres://postgres:password@vs-academy-product-db/product"
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - service-product-network

networks:
  service-product-network:
    driver: bridge
