version: '3'

services:

  postgres:
    container_name: vs-academy-product-db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - /srv/vs-academy-product-postgres:/var/lib/postgresql/data
    networks:
      - service-product-network

networks:
  service-product-network:
    driver: bridge
